### ISSUE TITLE
Roadmap for 5.1

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3687]
This is a roadmap for RT5.1.

Feature freeze and new branch around April 15, followed by a release candidate, and a final release a week later.

- [x] Pixelshift #3489
- [x] Fujifilm compressed raw support #3229 
- [x] Sharpen only edges needs review and speedup #3656. I will fix an old bug for 5.1. review and speedup is for 5.2
- [x] White Balance shows wrong values when opening a file whichs wb method is 'Auto', #3690
- [x] Changed "Processing profile operations -> Custom Profile Builder" to "Reset to default" #3760
- [x] Adding more zoom levels to the image editor #3763
- [x] Incorrect zooming with lens correction profiles #3765 
- [x] segfault on RAF files from Fuji S5 pro #3741 
- [x] Compiling with -Wall shows a large amount of warnings which should be fixed #3790 #3798
- [x] Update MacPorts instructions and macOS bundle scripts #3678 
- [x] Update rtexif with ExifTool 10.49 #3802 
- [x] colour balance differences​ between thumbnail and main preview #3804 
- [x] CLI #3691
- [x] filter-by-default #3843 
- [x] Auto Levels completely wrong for monochrome raw files, sigma raw files and canon mraw/sraw files #3863

**Comment by Hombre57** [comment]
May I suggest issue #3691 ? Just drop some comments there so I can finish it ASAP (99% done).

**Comment by heckflosse** [comment]
@Hombre57 added

**Comment by agriggio** [comment]
@Beep6581 how about #3760, #3763 and #3765? The first should be harmless (it just makes the action slightly more general), the second is (IMHO) ready, and the third fixes a long-standing and pretty annoying (for me) bug...

**Comment by Beep6581** [comment]
@agriggio agreed for the reasons you stated. I added them. I will try to test them in the evening.

**Comment by agriggio** [comment]
@Beep6581 thanks! :+1:

**Comment by Beep6581** [comment]
@agriggio one other thing. Yesterday, in the dead of the night, we convened in the woods, set fire to an effigy, chanted some spells, photographed a goat, and agreed that we would be happy to give you commit rights as you are active, helpful and get along well. It comes with but one snag - please don't line-wrap the code at 80 chars ;) If you agree and are willing, I will raise the cat by its leg, spin it over my head and grant you commit rights before midnight.

**Comment by agriggio** [comment]
@Beep6581 (and others) thanks a lot for your consideration! I'll be happy to contribute to the best of my possibilities, and I'm really honoured by your offer! I'm happy to accept and will do my best to not screw things up :wink:
Just one thing:

>  please don't line-wrap the code at 80 chars ;)

I won't do that (or at least I'll try to...). But be aware that it will be *really* hard for me not to, I just have it hardwired on my brain... (I have reasons for that, but won't elaborate as I'm sure they are irrelevant to you :-)

**Comment by Floessie** [comment]
@Beep6581 forgot to mention that those tribal rituals only happen twice a year at equinox. Welcome on board!

**Comment by agriggio** [comment]
@Floessie thanks!

**Comment by Beep6581** [comment]
The cat has been spun.

**Comment by heckflosse** [comment]
@agriggio Welcome! :+1:

**Comment by Hombre57** [comment]
Welcome 🖖

**Comment by Desmis** [comment]
Welcome :)

**Comment by agriggio** [comment]
Thank you all! :tada:

**Comment by heckflosse** [comment]
What is eta for 5.1?

**Comment by Beep6581** [comment]
Let's aim for a release candidate around April 9-16, and the final release a week or two later.

**Comment by Hombre57** [comment]
`rt-cli` removed from the roadmap as discussed on IRC with @heckflosse and @Beep6581 . It'll be part of 5.2.

**Comment by agriggio** [comment]
Hello @Hombre57 (and others), will the command-line flags be restored in the normal `rawtherapee` executable until `rt-cli` is ready? I think not having that would be a significant regression...

**Comment by Hombre57** [comment]
Well spotted! I'll finally have to have a look this evening.

**Comment by agriggio** [comment]
@Beep6581 is there a standard release process that you usually follow? E.g. freezing the `dev` branch, advertising release candidates on the forum and so on?

**Comment by Beep6581** [comment]
@agriggio does this sufficiently answer your question? https://github.com/Beep6581/RawTherapee/issues/3660#issue-204957934

**Comment by agriggio** [comment]
@Beep6581 thanks for the pointer! It answers most of my question :-)
I still have a doubt about what you consider to be "sufficiently tested" to go into `dev`. I understand that the general answer is "it depends", but specifically I'm wondering what to do with the open active branches we have now. More concretely:

- `denoise_uniform` (has been around for a long time)
- `thumbnail-black-white-levels` (fixes a bug, still limited testing but merging with `dev` would be a good way of testing more)
- `ipwavelet-heap-buffers` (ditto)

**Comment by agriggio** [comment]
BTW: perhaps that comment should also go to rawpedia, what do you think?

**Comment by heckflosse** [comment]
@agriggio :+1: for adding `thumbnail-black-white-levels` and `ipwavelet-heap-buffers`

**Comment by heckflosse** [comment]
I added #3804 to the roadmap

**Comment by Beep6581** [comment]
All known requirements for RawTherapee 5.1 have been satisfied. If there is anything you feel should go into this release, please speak now.

I will branch off and tag RawTherapee 5.1 RC1 (release candidate 1) tomorrow, and if no serious issues arise then we will release 5.1 final next week.

**Comment by agriggio** [comment]
:+1:

**Comment by agriggio** [comment]
I just noticed #3769 is still open...

**Comment by heckflosse** [comment]
I added #3863 because there is a safe patch

**Comment by Hombre57** [comment]
@agriggio Do you want to solve #3769 or should I do ?

**Comment by Beep6581** [comment]
I will be unavailable tomorrow, so I will try to release RC1 on Monday. Great to see more bug fixes!

**Comment by Floessie** [comment]
@Beep6581 @heckflosse I did a GCC 7.1 compile run of current `dev`: Good news, it compiles rather fine! There's only one warning:

```
[ 18%] Building CXX object rtengine/CMakeFiles/rtengine.dir/green_equil_RT.cc.o
In function ‘_ZN8rtengine14RawImageSource10cfa_linednEf._omp_fn.0’:
cc1plus: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
```

Best
Flössie

**Comment by heckflosse** [comment]
@Floessie Without a line number it's almost impossible to find the reason for the warning

**Comment by Floessie** [comment]
@heckflosse Yep, but the compiler won't give us one. Also only happens with OMP enabled. Might be a false positive. So, never mind.

**Comment by Beep6581** [comment]
Re: https://github.com/Beep6581/RawTherapee/issues/3873#issuecomment-301344516

@sguyader thank you. I asked you for two reasons:
1. when I looked at our Downloads section the most recent Windows build is from you and it works fine,
2. the only other person making Windows builds is @gaaned92 and I received no reply from him.
This is exactly why RT needs more than one person making builds per platform, so that if someone is unavailable someone else can step in.

You [made](https://discuss.pixls.us/t/rawtherapee-5-1-rc1-released/4146/5?u=morgan_hardwood) a 5.1-rc1 build, which tells me that everything works fine in Windows and now we can proceed to release 5.1 final. If I do so today, could I ask you again to make a 5.1 build? I won't ask again until 5.2 :) After making the 5.1 release I will wait with the announcement until we actually have some builds for people to download

P.S. Please do **not** update MSYS2, there seem to be compilation issues with the update.

**Comment by sguyader** [comment]
@Beep6581 ok I'll make the next builds as @gaaned92 didn't answer your requests.
I should get a new laptop in the following weeks, sonit will probably be easier for me to make builds for Windows in the future.

**Comment by Beep6581** [comment]
RawTherapee 5.1 is released.

@sguyader @Benitoite Could you "git checkout 5.1" and make a build please?

**Comment by Benitoite** [comment]
@Beep6581 
For macintosh 10.9+
https://filebin.net/kdwcikqfl5k8obdw/RawTherapee_OSX_10.9_64_5.1.zip

```
Version: 5.1
Branch: 5.1
Commit: f23d70fd
Commit date: 2017-05-15
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
```
![screen shot 2017-05-15 at 2 44 36 pm-1](https://cloud.githubusercontent.com/assets/17919239/26081127/4d2261f2-397e-11e7-8067-eec63fa96053.jpg)

**Comment by sguyader** [comment]
@Beep6581 
I just made the new Windows build for RT 5.1: https://filebin.net/n8nqv5cys7491dos

**Comment by Beep6581** [comment]
Thank you! The builds are live, RT5.1 is announced:
http://rawtherapee.com/blog/rawtherapee-5.1-released
