### ISSUE TITLE
Roadmap for 5.2

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3799]
This is a roadmap for RT5.2.

ETA 2017-07-23

- [x] Speedup for Microcontrast tool #3867
- [x] GIMP plugin #3880
- [x] macOS issues #3882
- [x] Windows crashes #3901
- [x] Large memory leak #3908
- [x] KLT choice between system and shipped #3912 
- [x] RT crashes in METM when a lot of Editors are opened #3937 
- [x] Monitor and printer ICC color profiles missing #3941 
- [x] new feature: open images in an already-running instance of RT #3946
- [x] `rawtherapee-cli` thinks `/dev/null` is a file #3948 
- [x] MEOW mode has some bugs #3957

**Comment by agriggio** [comment]
@Beep6581 how about the "high quality no matter what" button you mentioned in #3793 ?
Seems like a good idea to me.

**Comment by Hombre57** [comment]
Issue #3691 closed, RT-cli is finished. I'll update Rawpedia right now.

[PS] It's already in RT5.1 btw.

**Comment by Beep6581** [comment]
@agriggio sorry about not replying sooner, I must have missed your question. I only add issues which I know are being worked on. As far as I know, nobody is working on such a button, but if *someone* was, wink wink, then by all means!

**Comment by agriggio** [comment]
@Beep6581 I can work on that, but before I start maybe it could be a good time (after 5.1 is out) to talk about a "global" plan for where RT is going? e.g. if we want to try to refactor the pipeline then this comes later...

**Comment by Beep6581** [comment]
A number of issues have been fixed since 5.1, and some of them affect many people. It would therefore be a good idea to release 5.2 before the proposed pipeline unification #3897. I added some issues and PRs to the 5.2 roadmap. Feel free to add anything else which can be done realistically soon.

**Comment by agriggio** [comment]
#3880 is essentially done from my side (except for minor cosmetic fixes after @Floessie's review, which I'll do ASAP). Any objections to merging?

**Comment by heckflosse** [comment]
I vote for releasing 5.2 asap because a lot of crash issues (though not all) have been fixed or at least the likelyhood to crash has been reduced.

**Comment by agriggio** [comment]
fine for me, but I have a couple of features I'd like to discuss. one is an open pr already (remote option), another is the option to configure which tools are open. the first one would need some testing on Windows though...

**Comment by heckflosse** [comment]
@agriggio Alberto, I will test your open pr on Windows today

**Comment by Beep6581** [comment]
Agreed with everything - will test later today if time permits.

**Comment by Beep6581** [comment]
The release date for 5.2 is targeted about 2 weeks from now, depending on everyone's holidays.

**Comment by heckflosse** [comment]
We still have problems (crashes) caused by the massive amount of gdi handles used in METM and MEOW on windows (no problem on Linux here, don't know about MacOS).
I would like to restrict the number of open editors on Windows to 8 in METM and to 5 in MEOW for 5.2.
That should avoid the crashes caused by reaching the 10000 gdi handle limit on Windows.
When 5.2 is released I can make further tries to find the culprits.

Any objections?

**Comment by Hombre57** [comment]
No objection.

**Comment by heckflosse** [comment]
@Hombre57 Btw: I found out that each adjuster needs 4 handles and each file chooser button needs 16 handles.

Edit: And, the 4 handles needed by adjuster are needed by the spinbutton inside the adjuster

**Comment by Hombre57** [comment]
Do we know the number of handle for Linux ? If that's a different value between both OS, then you should still consider a leak in Gtk3. Does FireFox use Gtk ? It's quite unstable here (Win7) when 20 tab opened.

**Comment by Hombre57** [comment]
Adjusters uses standard Gtk widgets, as well as the file chooser, so it can't be a wrong custom GUI design I guess.

**Comment by heckflosse** [comment]
I absolutely agree with you that it should not be wrong custom GUI design!

**Comment by Floessie** [comment]
@Hombre57 
> Does FireFox use Gtk ? It's quite unstable here (Win7) when 20 tab opened.

Debian updated to Firefox 52 ESR lately. It's GTK3 now, which can be clearly seen due to a black frame when opening (same as the RT preferences window behavior) and unfitting theming under XFCE (which is still mostly GTK2). Ah, and it takes longer to render...

**Comment by heckflosse** [comment]
@agriggio Alberto, I added #3946

**Comment by agriggio** [comment]
thanks!

**Comment by heckflosse** [comment]
I added #3957 because @Hombre57, @Luncher91 (kudos for his tests), and I are working on this and are quite close to a complete fix. Even if it's not a complete fix, it will be much better than before.
If we are not able to fix it in time, we can still remove it from the roadmap.

**Comment by heckflosse** [comment]
I removed `Pixel Shift/Multi-frame raw image thumbnail icons` from the roadmap for 5.2

**Comment by Beep6581** [comment]
ETA 2017-07-23

**Comment by heckflosse** [comment]
Less than 4 month from the roadmap to the release. Not so bad :+1:

**Comment by heckflosse** [comment]
I would like to point out some things for the 5.2 release notes ordered by name of authors;

1) gimp plugin (by agriggio)
2) remote app (by agriggio)
3) 4x speedup for microcontrast (by heckflosse)
4) some speedups and reductions of memory usage for pixel shift processing (by heckflosse)
5) large speedup and improved stability when using folders with a lot of files (by heckflosse)
6) improved MEOW mode (by heckflosse and Hombre57)

to be continued. .. too late now...

**Comment by Beep6581** [comment]
Thank you @heckflosse As this release involves a lot of bug fixes whose commit messages are not always meaningful to me, I will appreciate help with the changelog.

**Comment by heckflosse** [comment]
7. improved stability in METM on Windows
8. wasn't there a serious improvement for lcp correction (by agriggio)?

**Comment by agriggio** [comment]
@heckflosse about 8, it's more empirical than serious :wink:

Basically, to my understanding the Adobe LCP specs are underspecified and do not exactly describe how to properly select the correct correction coefficients when there is no exact match (or there are multiple matching entries) in the LCP, nor how to take into account the error information that is stored in the entries. Therefore, we have to resort to trial-and-error.

The old code was taking a "pessimistic" approach, discarding a lot of entries with an error information above a given threshold (under the assumption that the data was invalid).

My experiment was to take a more "optimistic" view, essentially trusting that the LCP profile provides good data. According to the users who tried it, this seems to give better results when using the LCP profiles shipped with the Adobe products.

**Comment by heckflosse** [comment]
@agriggio Concerning `new feature: open images in an already-running instance of RT`. It would be interesting to add the possibility to add images to the queue of an already-running instance of RT.
Just an idea...

**Comment by jeffersonfr** [comment]
- Important feature 1: masks, zones or componentes (r, g, b, saturation, luminosity, ...) to isolate regions of image
- Important feature 2: differents versions of an image
- Important feature 3: blend modes

With this features the RawTherapee will be the better tool to edit raw images available !
